/* SPDX-License-Identifier: BSD-2-Clause */
/* Prints the format constants the portable reader keeps as private macros.
 * Including the translation unit is deliberate: the values under test are
 * the ones the reader compiles with, not a second copy. */
#include "../reader.c"
#include <stdio.h>

#define SHOW(name) printf(#name " %llu\n", (unsigned long long)(name))

int main(void)
{
    SHOW(AFSPR_HEADER_SIZE);
    SHOW(AFSPR_CHECKSUM_OFFSET);
    SHOW(AFSPR_HEADER_VERSION);
    SHOW(AFSPR_BLOCK_TYPE_IDENT);
    SHOW(AFSPR_BLOCK_TYPE_CHECKPOINT);
    SHOW(AFSPR_BLOCK_TYPE_OBJECT);
    SHOW(AFSPR_BLOCK_TYPE_SECURITY);
    SHOW(AFSPR_BLOCK_TYPE_TREE);
    SHOW(AFSPR_BLOCK_TYPE_INTENT);
    SHOW(AFSPR_BLOCK_TYPE_BITMAP);
    SHOW(AFSPR_BLOCK_TYPE_REGION_DESCRIPTOR);
    SHOW(AFSPR_CHECKSUM_CRC32C);
    SHOW(AFSPR_IDENT_CURRENT_PAYLOAD);
    SHOW(AFSPR_CHECKPOINT_PAYLOAD);
    SHOW(AFSPR_OBJECT_FIRST_DYNAMIC);
    SHOW(AFSPR_MIN_REGION_BLOCKS);
    SHOW(AFSPR_MAX_REGION_BLOCKS);
    SHOW(AFSPR_BITMAP_PAGE_BLOCKS);
    SHOW(AFSPR_BOOTSTRAP_BLOCKS);
    SHOW(AFSPR_DESCRIPTOR_SLOTS);
    SHOW(AFSPR_BITMAP_SLOTS);
    SHOW(AFSPR_TREE_FIXED_PAYLOAD);
    SHOW(AFSPR_TREE_ITEM_FIXED);
    SHOW(AFSPR_TREE_MAX_LEVEL);
    SHOW(AFSPR_TREE_MAX_KEY);
    SHOW(AFSPR_TREE_KIND_OBJECT_MAP);
    SHOW(AFSPR_TREE_KIND_DIRECTORY);
    SHOW(AFSPR_TREE_KIND_EXTENT_MAP);
    SHOW(AFSPR_TREE_KIND_ALLOCATION_ROOT);
    SHOW(AFSPR_ALLOCATION_VALUE_SIZE);
    SHOW(AFSPR_REGION_DESCRIPTOR_FIXED);
    SHOW(AFSPR_BITMAP_FIXED);
    SHOW(AFSPR_OBJECT_PAYLOAD);
    SHOW(AFSPR_SECURITY_REF_SIZE);
    SHOW(AFSPR_SECURITY_SEGMENT_FIXED);
    SHOW(AFSPR_MAX_DIRECT_BLOCKS);
    SHOW(AFSPR_EXTENT_VALUE_SIZE);
    SHOW(AFSPR_LOG_FIXED_PAYLOAD);
    SHOW(AFSPR_LOG_OP_FIXED);
    SHOW(AFSPR_LOG_CURRENT_VERSION);
    SHOW(AFSPR_LOG_MAX_EXTENTS);
    SHOW(AFSPR_LOG_MAX_OPS);
    SHOW(AFSPR_MAX_SECURITY_DESCRIPTOR_BYTES);
    SHOW(AFSPR_BLOCK_TYPE_ATTRIBUTES);
    SHOW(AFSPR_ATTRIBUTE_REF_SIZE);
    SHOW(AFSPR_OBJECT_FLAG_ATTRIBUTES);
    SHOW(AFSPR_MAX_ATTRIBUTE_SET_BYTES);
    SHOW(AFSPR_ATTRIBUTE_SET_FORMAT);
    SHOW(AFSPR_BLOCK_TYPE_RECLAIM_ROOT);
    SHOW(AFSPR_BLOCK_TYPE_RECLAIM_SEGMENT);
    SHOW(AFSPR_BLOCK_TYPE_RECLAIM_TABLE);
    SHOW(AFSPR_RECLAIM_ENTRY_SIZE);
    SHOW(AFSPR_RECLAIM_REF_SIZE);
    SHOW(AFSPR_RECLAIM_ROOT_FIXED);
    SHOW(AFSPR_RECLAIM_SEALED_FIXED);
    SHOW(AFSPR_RECLAIM_ROOT_VERSION);
    SHOW(AFSPR_RECLAIM_SEGMENT_ENTRY_CAP);
    SHOW(AFSPR_RECLAIM_TABLE_REF_CAP);
    return 0;
}
