/* SPDX-License-Identifier: BSD-2-Clause */

/* The DOS error numbers the AROS adapter answers with, one line each. Two
 * readers hold both sides to this list: error_numbers.c checks every line
 * against the target's <dos/dos.h> at compile time, and the Rust test
 * afsplus-aros-ffi/tests/error_numbers.rs checks every line against
 * ArosError, which it matches exhaustively. A number can then differ from
 * the header only if this file is wrong, and then the C side does not
 * compile. The includer defines AFSPLUS_DOS_ERROR(name, number). */
AFSPLUS_DOS_ERROR(ERROR_UNKNOWN, 100)
AFSPLUS_DOS_ERROR(ERROR_NO_FREE_STORE, 103)
AFSPLUS_DOS_ERROR(ERROR_BAD_NUMBER, 115)
AFSPLUS_DOS_ERROR(ERROR_OBJECT_IN_USE, 202)
AFSPLUS_DOS_ERROR(ERROR_OBJECT_EXISTS, 203)
AFSPLUS_DOS_ERROR(ERROR_DIR_NOT_FOUND, 204)
AFSPLUS_DOS_ERROR(ERROR_OBJECT_NOT_FOUND, 205)
AFSPLUS_DOS_ERROR(ERROR_OBJECT_TOO_LARGE, 207)
AFSPLUS_DOS_ERROR(ERROR_ACTION_NOT_KNOWN, 209)
AFSPLUS_DOS_ERROR(ERROR_INVALID_COMPONENT_NAME, 210)
AFSPLUS_DOS_ERROR(ERROR_INVALID_LOCK, 211)
AFSPLUS_DOS_ERROR(ERROR_OBJECT_WRONG_TYPE, 212)
AFSPLUS_DOS_ERROR(ERROR_DISK_WRITE_PROTECTED, 214)
AFSPLUS_DOS_ERROR(ERROR_DIRECTORY_NOT_EMPTY, 216)
AFSPLUS_DOS_ERROR(ERROR_SEEK_ERROR, 219)
AFSPLUS_DOS_ERROR(ERROR_COMMENT_TOO_BIG, 220)
AFSPLUS_DOS_ERROR(ERROR_DISK_FULL, 221)
AFSPLUS_DOS_ERROR(ERROR_WRITE_PROTECTED, 223)
AFSPLUS_DOS_ERROR(ERROR_NOT_A_DOS_DISK, 225)
AFSPLUS_DOS_ERROR(ERROR_NO_MORE_ENTRIES, 232)
AFSPLUS_DOS_ERROR(ERROR_IS_SOFT_LINK, 233)
AFSPLUS_DOS_ERROR(ERROR_RECORD_NOT_LOCKED, 240)
AFSPLUS_DOS_ERROR(ERROR_LOCK_COLLISION, 241)
