##begin config
basename AfsRam
version 0.1
libbase AfsRamBase
libbasetype struct AfsRamBase
sysbase_field sys_base
residentpri -39
beginio_func AfsRam_BeginIO
abortio_func AfsRam_AbortIO
##end config

##begin cdefprivate
#include "afsram_device.h"
##end cdefprivate
