name = "boot-safe"
description = "Feature set appropriate for boot and recovery volumes."

allow_catalog = false
allow_change_stream = false
allow_inline_data = false
allow_xattrs = false
allow_sparse = false
allow_intent_log = true
allow_intent_log_data_updates = true
allow_shared_extents = false
allow_data_policy = false
allow_orphan_directory = true
require_metadata_journal = true
require_metadata_checksums = true
