name = "workstation"
description = "Default modern AROS profile."

allow_catalog = true
allow_change_stream = true
allow_inline_data = false
allow_xattrs = true
allow_sparse = true
allow_intent_log = true
allow_intent_log_data_updates = true
allow_shared_extents = true
allow_data_policy = true
allow_orphan_directory = true
require_metadata_journal = true
require_metadata_checksums = true
allow_persistent_snapshots = true
allow_security_descriptors = true
