#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 John Knipper
# Derived from aros-apple-silicon/tools/check-doc-links by the same author.
"""Check the AFS+ documentation contract: links, anchors, TOCs, indexes, cross-references.

Every check is repository-local and offline. The rules are written for people
in ``docs/DOCUMENTATION.md``; this script enforces the mechanical part:

1. every relative link resolves to a file or directory, and every
   ``#fragment`` on a Markdown link resolves to a GitHub-style heading anchor;
2. every Markdown file longer than ``TOC_MIN_LINES`` carries a
   ``<!-- toc -->`` ... ``<!-- /toc -->`` block that matches its headings
   (``--write-toc`` inserts or regenerates the blocks);
3. every ``ADR-NNN`` mention resolves to ``adr/ADR-NNN-*.md``;
4. every ``MNN`` milestone mention is a row of ``implementation/milestones.md``;
5. ``adr/README.md`` carries a generated index of every ADR between
   ``<!-- adr-index -->`` and ``<!-- /adr-index -->`` (``--write-adr-index``
   regenerates it);
6. every design document, test plan and proposal opens with the navigation
   block described in ``docs/DOCUMENTATION.md``;
7. every file under ``tools/`` has a row in ``tools/README.md``, every test
   plan a row in ``testing/README.md``, every design document a row in
   ``docs/README.md`` and every implementation document a row in
   ``implementation/README.md``;
8. ``Status:`` lines appear only in ADRs, the ``## Status`` table of
   ``README.md`` has at most five rows, and every cell of the milestone table
   fits on one line.

``--journey`` additionally reports, without failing, how many journey words
("now", "currently", "still", ...) each file carries; they belong in
``NOTES.md`` only.

Exit status is non-zero when any problem is reported. Problems are printed one
per line after a single summary line.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys
from urllib.parse import unquote


EXCLUDED_TREES = {".git", "build", "crates", "native", "target", "vendor"}
TOC_MIN_LINES = 150
README_STATUS_MAX_ROWS = 5
MILESTONE_CELL_MAX_CHARS = 160
NAV_BLOCK_WINDOW = 8  # the block starts within this many lines of the title

LINK = re.compile(r"!?\[[^\]]*\]\(([^)]+)\)")
HEADING = re.compile(r"^(#{1,6})\s+(.+?)\s*#*\s*$")
SCHEME = re.compile(r"^[a-z][a-z0-9+.-]*:", re.IGNORECASE)
FENCE = re.compile(r"^\s*(```|~~~)")
TOC_START = re.compile(r"^<!--\s*toc(?:\s+depth=([1-6]))?\s*-->\s*$")
TOC_END = re.compile(r"^<!--\s*/toc\s*-->\s*$")
ADR_INDEX_START = re.compile(r"^<!--\s*adr-index\s*-->\s*$")
ADR_INDEX_END = re.compile(r"^<!--\s*/adr-index\s*-->\s*$")
ADR_REF = re.compile(r"\bADR-(\d{3})\b")
ADR_TITLE = re.compile(r"^#\s+ADR-(\d{3}):\s*(.+?)\s*$")
ADR_RELATION = re.compile(
    r"^(Supersedes|Superseded by|Amends|Amended by):\s*(.+?)\s*$"
)
MILESTONE_REF = re.compile(r"\bM(\d{2})\b")
MILESTONE_ROW = re.compile(r"^\|\s*M(\d{2})\s*\|")
STATUS_LINE = re.compile(r"^Status:")
NAV_BLOCK = re.compile(r"^>\s*\*\*ADRs:\*\*")
NAV_MILESTONES = re.compile(r"\*\*Milestones:\*\*")
JOURNEY = re.compile(
    r"\b(now|currently|still|remains?|no longer|the latest|"
    r"was superseded by|so far|to date|at the moment|recently|previously)\b",
    re.IGNORECASE,
)

ADR_INDEX_DEFAULT = """# Architecture Decision Records

Decision records are immutable except for their status and relation lines.
Numbers are never reused. The table is generated by
`tools/check-docs.py --write-adr-index`; edit the ADRs, not the table.

<!-- adr-index -->
<!-- /adr-index -->
"""


def github_slug(text: str) -> str:
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"<[^>]+>", "", text).strip().lower()
    text = re.sub(r"[`*_~]", "", text)
    text = "".join(
        character for character in text
        if character.isalnum() or character in " -_"
    )
    return re.sub(r"\s", "-", text)


def markdown_files(root: Path) -> list[Path]:
    return sorted(
        path for path in root.rglob("*.md")
        if not any(
            part in EXCLUDED_TREES for part in path.relative_to(root).parts
        )
    )


def read_lines(path: Path) -> list[str]:
    return path.read_text(encoding="utf-8").splitlines()


def headings(lines: list[str]) -> list[tuple[int, int, str, str]]:
    """Return (line index, level, text, anchor) for headings outside code fences."""
    counts: dict[str, int] = {}
    found: list[tuple[int, int, str, str]] = []
    in_fence = False
    for index, line in enumerate(lines):
        if FENCE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        match = HEADING.match(line)
        if match is None:
            continue
        text = match.group(2)
        base = github_slug(text)
        count = counts.get(base, 0)
        counts[base] = count + 1
        found.append((index, len(match.group(1)), text,
                      base if count == 0 else f"{base}-{count}"))
    return found


def heading_anchors(path: Path) -> set[str]:
    return {anchor for _, _, _, anchor in headings(read_lines(path))}


def strip_fences(text: str) -> str:
    """Remove fenced code blocks; links and identifiers inside them are examples."""
    out: list[str] = []
    in_fence = False
    for line in text.splitlines():
        if FENCE.match(line):
            in_fence = not in_fence
            continue
        if not in_fence:
            out.append(line)
    return "\n".join(out)


def destination(raw: str) -> str:
    value = raw.strip()
    if value.startswith("<"):
        closing = value.find(">")
        if closing != -1:
            return value[1:closing]
    for separator in (' "', " '"):
        if separator in value:
            value = value.split(separator, 1)[0]
    return value


def render_toc(lines: list[str], depth: int, toc_line: int) -> list[str]:
    rendered: list[str] = []
    for index, level, text, anchor in headings(lines):
        if level < 2 or level > depth or index < toc_line:
            continue
        rendered.append(f"{'  ' * (level - 2)}- [{text}](#{anchor})")
    return rendered


def first_h2_index(lines: list[str]) -> int:
    in_fence = False
    for index, line in enumerate(lines):
        if FENCE.match(line):
            in_fence = not in_fence
            continue
        if not in_fence and line.startswith("## "):
            return index
    return -1


def process_toc(path: Path, write: bool) -> tuple[str, bool]:
    """Return (state, stale) where state is 'present', 'absent' or 'inserted'."""
    lines = read_lines(path)
    start = end = -1
    depth = 3
    for index, line in enumerate(lines):
        match = TOC_START.match(line)
        if match and start == -1:
            start = index
            if match.group(1):
                depth = int(match.group(1))
        elif TOC_END.match(line) and start != -1:
            end = index
            break
    if start == -1:
        if not write or len(lines) <= TOC_MIN_LINES:
            return "absent", False
        h2 = first_h2_index(lines)
        if h2 == -1:
            return "absent", False
        block = ["<!-- toc -->", ""] + render_toc(lines, depth, h2) + [
            "", "<!-- /toc -->", ""]
        lines[h2:h2] = block
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return "inserted", False
    if end == -1:
        raise ValueError(f"{path}: <!-- toc --> without <!-- /toc -->")
    expected = render_toc(lines, depth, start)
    current = [line for line in lines[start + 1:end] if line.strip()]
    stale = current != expected
    if stale and write:
        lines[start + 1:end] = [""] + expected + [""] if expected else [""]
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return "present", stale


def adr_records(root: Path) -> list[dict[str, str]]:
    records: list[dict[str, str]] = []
    for path in sorted((root / "adr").glob("ADR-*.md")):
        lines = read_lines(path)
        title = ""
        number = ""
        status: list[str] = []
        relations: list[str] = []
        in_status = False
        for line in lines:
            if line.startswith("## "):
                break
            match = ADR_TITLE.match(line)
            if match:
                number, title = match.groups()
                continue
            if STATUS_LINE.match(line):
                status.append(line.split(":", 1)[1].strip())
                in_status = True
                continue
            relation = ADR_RELATION.match(line)
            if relation:
                in_status = False
                relations.append(
                    f"{relation.group(1).lower()} {relation.group(2)}")
                continue
            if in_status and line.strip():
                status.append(line.strip())
            else:
                in_status = False
        records.append({
            "file": path.name,
            "number": number or path.name[4:7],
            "title": title,
            "status": " ".join(status),
            "relations": "; ".join(relations),
        })
    return records


def link_adr_refs(text: str, records: dict[str, str]) -> str:
    return ADR_REF.sub(
        lambda match: (
            f"[ADR-{match.group(1)}]({records[match.group(1)]})"
            if match.group(1) in records else match.group(0)
        ),
        text,
    )


def render_adr_index(root: Path) -> list[str]:
    records = adr_records(root)
    files = {record["number"]: record["file"] for record in records}
    rows = ["", "| ADR | Title | Status | Superseded by / amends |",
            "|---|---|---|---|"]
    for record in records:
        status = record["status"].replace("|", "\\|")
        relations = link_adr_refs(record["relations"], files) or "—"
        rows.append(
            f"| [ADR-{record['number']}]({record['file']}) | "
            f"{record['title'].replace('|', chr(92) + '|')} | {status} | "
            f"{relations} |"
        )
    rows.append("")
    return rows


def process_adr_index(root: Path, write: bool, problems: list[str]) -> int:
    index = root / "adr" / "README.md"
    if not index.exists():
        if write:
            index.write_text(ADR_INDEX_DEFAULT, encoding="utf-8")
        else:
            problems.append("adr/README.md (missing; run "
                            "tools/check-docs.py --write-adr-index)")
            return 0
    lines = read_lines(index)
    start = end = -1
    for position, line in enumerate(lines):
        if ADR_INDEX_START.match(line) and start == -1:
            start = position
        elif ADR_INDEX_END.match(line) and start != -1:
            end = position
            break
    if start == -1 or end == -1:
        problems.append("adr/README.md (missing <!-- adr-index --> ... "
                        "<!-- /adr-index --> markers)")
        return 0
    expected = render_adr_index(root)
    current = lines[start + 1:end]
    if [line for line in current if line.strip()] != [
            line for line in expected if line.strip()]:
        if write:
            lines[start + 1:end] = expected
            index.write_text("\n".join(lines) + "\n", encoding="utf-8")
        else:
            problems.append("adr/README.md (stale ADR index; run "
                            "tools/check-docs.py --write-adr-index)")
    return len(expected) - 4


def milestone_ids(root: Path) -> set[str]:
    path = root / "implementation" / "milestones.md"
    if not path.exists():
        return set()
    return {
        match.group(1)
        for line in read_lines(path)
        if (match := MILESTONE_ROW.match(line))
    }


def needs_nav_block(relative: Path) -> bool:
    if len(relative.parts) != 2 or relative.suffix != ".md":
        return False
    folder, name = relative.parts
    if name == "README.md":
        return False
    if folder == "docs":
        return name != "DOCUMENTATION.md"
    return folder in {"testing", "proposals"}


def check_nav_block(path: Path, root: Path, problems: list[str]) -> bool:
    relative = path.relative_to(root)
    if not needs_nav_block(relative):
        return False
    lines = read_lines(path)
    start = next((index for index, line in enumerate(lines[:NAV_BLOCK_WINDOW])
                  if NAV_BLOCK.match(line)), -1)
    block: list[str] = []
    if start != -1:
        for line in lines[start:]:
            if not line.startswith(">"):
                break
            block.append(line)
    if start == -1 or not any(NAV_MILESTONES.search(line) for line in block):
        problems.append(
            f"{relative} (missing the '> **ADRs:** ... **Milestones:** ...' "
            "navigation block after the title; see docs/DOCUMENTATION.md)"
        )
    return True


def check_index_rows(root: Path, index: Path, members: list[Path],
                     problems: list[str]) -> None:
    label = index.relative_to(root)
    if not index.exists():
        problems.append(f"{label} (missing index)")
        return
    text = strip_fences(index.read_text(encoding="utf-8"))
    for member in members:
        if member.name not in text:
            problems.append(
                f"{label} has no row for {member.relative_to(root)}")


def check_status_rules(root: Path, files: list[Path],
                       problems: list[str]) -> None:
    for path in files:
        relative = path.relative_to(root)
        if relative.parts[0] == "adr" or relative.name == "NOTES.md" or (
                len(relative.parts) > 1 and relative.parts[1] == "memos"):
            continue
        for number, line in enumerate(
                strip_fences(path.read_text(encoding="utf-8")).splitlines(),
                start=1):
            if STATUS_LINE.match(line):
                problems.append(
                    f"{relative}:{number} ('Status:' lines belong to ADRs; "
                    "state lives in implementation/milestones.md)")

    readme = root / "README.md"
    if readme.exists():
        rows = 0
        in_status = False
        for line in read_lines(readme):
            if line.startswith("## "):
                in_status = line.strip().lower() == "## status"
                continue
            if in_status and line.startswith("|") and not re.match(
                    r"^\|[\s:-]+\|", line):
                rows += 1
        rows = max(rows - 1, 0)  # header row
        if rows > README_STATUS_MAX_ROWS:
            problems.append(
                f"README.md (## Status has {rows} table rows; at most "
                f"{README_STATUS_MAX_ROWS} allowed, details belong to "
                "implementation/milestones.md)")

    milestones = root / "implementation" / "milestones.md"
    if milestones.exists():
        for number, line in enumerate(read_lines(milestones), start=1):
            if not MILESTONE_ROW.match(line):
                continue
            for cell in line.strip().strip("|").split("|"):
                if len(cell.strip()) > MILESTONE_CELL_MAX_CHARS:
                    problems.append(
                        f"implementation/milestones.md:{number} (cell longer "
                        f"than {MILESTONE_CELL_MAX_CHARS} characters; keep "
                        "one line: 'state — what passes; what is open')")
                    break


def journey_report(root: Path, files: list[Path]) -> int:
    total = 0
    rows: list[tuple[int, str]] = []
    for path in files:
        relative = path.relative_to(root)
        if relative.name == "NOTES.md" or (
                len(relative.parts) > 1 and relative.parts[1] == "memos"):
            continue
        count = len(JOURNEY.findall(strip_fences(
            path.read_text(encoding="utf-8"))))
        if count:
            rows.append((count, str(relative)))
            total += count
    for count, name in sorted(rows, reverse=True):
        print(f"journey {count:4d} {name}")
    return total


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--root", type=Path,
        default=Path(__file__).resolve().parents[1],
        help="repository root (defaults to this tool's repository)",
    )
    parser.add_argument(
        "--write-toc", action="store_true",
        help="insert missing and regenerate stale <!-- toc --> blocks",
    )
    parser.add_argument(
        "--write-adr-index", action="store_true",
        help="regenerate the ADR table in adr/README.md",
    )
    parser.add_argument(
        "--write", action="store_true",
        help="same as --write-toc --write-adr-index",
    )
    parser.add_argument(
        "--journey", action="store_true",
        help="report journey-word counts per file (advisory, never fails)",
    )
    arguments = parser.parse_args()
    write_toc = arguments.write_toc or arguments.write
    write_adr_index = arguments.write_adr_index or arguments.write
    root = arguments.root.resolve()
    problems: list[str] = []

    # 5. ADR index first, so its links are checked on the final text.
    adr_count = process_adr_index(root, write_adr_index, problems)

    files = markdown_files(root)

    # 2. Tables of contents next, so anchors are computed on the final text.
    toc_files = toc_stale = 0
    for path in files:
        state, stale = process_toc(path, write_toc)
        relative = path.relative_to(root)
        if state == "absent":
            if len(read_lines(path)) > TOC_MIN_LINES and first_h2_index(
                    read_lines(path)) != -1:
                problems.append(
                    f"{relative} (longer than {TOC_MIN_LINES} lines without a "
                    "<!-- toc --> block; run tools/check-docs.py --write-toc)")
            continue
        toc_files += 1
        if stale:
            toc_stale += 1
            problems.append(
                f"{relative} (stale toc; run tools/check-docs.py --write-toc)")

    anchors = {path.resolve(): heading_anchors(path) for path in files}

    # 1. Links and fragments.
    checked = external = 0
    for source in files:
        content = strip_fences(source.read_text(encoding="utf-8"))
        for match in LINK.finditer(content):
            raw = destination(match.group(1))
            if SCHEME.match(raw) or raw.startswith("//"):
                external += 1
                continue
            target_text, separator, fragment = raw.partition("#")
            target = source if not target_text else (
                source.parent / unquote(target_text)
            )
            checked += 1
            label = f"{source.relative_to(root)} -> {raw}"
            if not target.exists():
                problems.append(f"{label} (missing)")
                continue
            if (separator and fragment and target.is_file() and
                    target.suffix.lower() == ".md" and
                    unquote(fragment).lower() not in
                    anchors.get(target.resolve(), set())):
                problems.append(f"{label} (missing anchor)")

    # 3. ADR references.
    adr_files = {record["number"] for record in adr_records(root)}
    adr_refs = 0
    for path in files:
        for match in ADR_REF.finditer(
                strip_fences(path.read_text(encoding="utf-8"))):
            adr_refs += 1
            if match.group(1) not in adr_files:
                problems.append(
                    f"{path.relative_to(root)} -> ADR-{match.group(1)} "
                    "(no such adr/ADR-NNN-*.md)")

    # 4. Milestone references.
    milestones = milestone_ids(root)
    milestone_refs = 0
    for path in files:
        for match in MILESTONE_REF.finditer(
                strip_fences(path.read_text(encoding="utf-8"))):
            milestone_refs += 1
            if match.group(1) not in milestones:
                problems.append(
                    f"{path.relative_to(root)} -> M{match.group(1)} "
                    "(no such row in implementation/milestones.md)")

    # 6. Navigation blocks.
    nav_files = sum(check_nav_block(path, root, problems) for path in files)

    # 7. Index coverage.
    tools_dir = root / "tools"
    check_index_rows(root, tools_dir / "README.md", sorted(
        path for path in tools_dir.iterdir()
        if path.is_file() and path.name != "README.md"), problems)
    for folder in ("testing", "docs", "implementation"):
        directory = root / folder
        check_index_rows(root, directory / "README.md", sorted(
            path for path in directory.glob("*.md")
            if path.name != "README.md"), problems)

    journey = journey_report(root, files) if arguments.journey else None

    result = "PASS" if not problems else "FAIL"
    summary = (
        f"check-docs result={result} markdown={len(files)} links={checked} "
        f"external={external} toc_files={toc_files} toc_stale={toc_stale} "
        f"adrs={adr_count} adr_refs={adr_refs} "
        f"milestone_refs={milestone_refs} nav_files={nav_files} "
        f"problems={len(problems)}"
    )
    if journey is not None:
        summary += f" journey_words={journey}"
    print(summary)
    for item in problems:
        print(item)
    return 1 if problems else 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, UnicodeError, ValueError) as error:
        print(f"check-docs result=FAIL reason={error}", file=sys.stderr)
        raise SystemExit(1)
